<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Songbook')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/assets/css/style.css')
                        /*  ->prependStylesheet($this->basePath() . '/assets/bower_components/bootstrap/dist/css/bootstrap-theme.min.css') */
                        ->prependStylesheet($this->basePath() . '/assets/bower_components/bootstrap/dist/css/bootstrap.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/assets/bower_components/bootstrap/dist/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/assets/bower_components/jquery/dist/jquery.min.js');
        ?>

    </head>
    <body>
        <div class="container-fluid">
			<div class="row">
			<div class="col-sm-2 side-menu">
				<ul class="row nav">
					<li class="site-logo">Songbook</li>
					<li>Concert</li>
				</ul>
			</div>
			<div class="col-sm-10">
            <?php echo $this->content; ?>
			<footer>
				<p>&copy; Songbook 2014&ndash;<?php echo date('Y') ?> by manro</p>
			</footer>
			</div>
			</div>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
