<?php
/*
 @var $concert \Songbook\Entity\Concert
 */
?>

<div id="concert_composite_block" class="concert_composite_block concert-composite-block row">


<div class="wrapper">
<?php
$element = new \Zend\Form\Element\Text('concert-id');
$element->setAttribute('type', 'hidden');
$element->setAttribute('value', $concert->id);
$element->setAttribute('id', 'concert-id');
?>

<?= $this->formInput($element); ?>

<div class="col-sm-8">
<div id="search-block">

<?php
$searchElement = new \Zend\Form\Element\Text('search-song');
$searchElement->setAttributes(array('type' => 'text', 'id' => 'search-song', 'class' => 'form-control search'));
$searchElement->setLabelAttributes(array('class' => 'control-label col-sm-1'));
$searchElement->setLabel("Поиск:");
?>

<div class="form-horizontal">
<div class="form-group">
<?= $this->formLabel($searchElement); ?>

<div class="col-sm-11">
<?= $this->formInput($searchElement); ?>
</div>
</div>
</div>

</div>

<div id="master-song-block">

<?php
$element = new \Zend\Form\Element\Text('master-song-id');
$element->setAttribute('type', 'hidden');
$element->setAttribute('id', 'master-song-id');
?>

<?= $this->formInput($element); ?>

<div class="cont">
<div class="favorite-header-cont"></div>
<div class="info-cont"></div>
<div class="headers-cont"></div>
</div>

<button id="master-song-add-to-concert" class="btn btn-primary" name="button" type="button" style="display: none;">Добавить</button>

<hr/>
</div>
<div id="concert-block">

<?php
$buttonNewConcert = new \Zend\Form\Element\Button('button');
$buttonNewConcert->setLabel("Новый концерт");
$buttonNewConcert->setAttributes(array('type' => 'button', 'id' => 'concert-create', 'class' => 'btn btn-success'));

$buttonNewConcertGroup = new \Zend\Form\Element\Button('button');
$buttonNewConcertGroup->setAttributes(array('type' => 'button', 'id' => 'concert-group-create', 'class' => 'btn btn-default'));
$buttonNewConcertGroup->setLabel("Сгруппировать");

$buttonRemoveConcertGroup = new \Zend\Form\Element\Button('button');
$buttonRemoveConcertGroup->setAttributes(array('type' => 'button', 'id' => 'concert-group-delete', 'class' => 'btn btn-default'));
$buttonRemoveConcertGroup->setLabel("Удалить группу");
?>

<h3>Репертуар на <?= date('j.m.Y', $concert->time); ?></h3>

<div class="btn-toolbar">
<div class="btn-group">
<?= $this->formButton($buttonNewConcert); ?>
</div>
<div class="btn-group">
<?= $this->formButton($buttonRemoveConcertGroup); ?>
<?= $this->formButton($buttonNewConcertGroup); ?>
</div>

<div class="btn-group">
<a href="<?= $this->url('default', array('controller' => 'concert', 'action' => 'content-process', 'id' => $concert->id )) ?>" class="btn btn-default">Операции с файлами</a>
</div>
</div>

<?= $this->partial('songbook/partials/concert-items.phtml', array('items' => $songService->getCollectionByConcert($concert))); ?>


</div>
</div>
<div class="col-sm-4">
<div id="long-not-used-cont">
<h4 class="header" style="display:none">Давно не исполнялись</h4>
</div>

<div id="top-popular-cont">
<h4 class="header" style="display:none">Топ популярных</h4>
</div>

<div id="taken-last-months-cont">
	<h4 class="header" style="display:none">Новые в течение последних {amount} месяцев</h4>
</div>

<div id="used-last-months-cont">
<h4 class="header" style="display:none">Использовались последние {amount} месяца</h4>
</div>




</div>
<div class="clear"></div>
</div>
</div>
